### ISSUE TITLE
Stop playing when one track is complete

### ISSUE THREAD

**Issue by heidariedu** [googlesamples/android-MediaBrowserService#11]
hello, in simple media browser service project , Stop playing when one track is complete.
how i can set loop in this codes

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
