### ISSUE TITLE
Notification is recreated everytime and blinks

### ISSUE THREAD

**Issue by gmendezdot** [googlesamples/android-MediaBrowserService#2]
In MusicService.java in line 503 is where we create the notification and everytime we pause the notification is recreated. I added Previous and Next to my own project and I get the same problem, it looks like a blink. I tried not to call startForeground everytime to avoid the blinking but if i close the app then the music stops because I'm not in foreground anymore.

I tried not to declare global some of the variables but it didn't work.

Any solution to the annoying blinking problem?

**Comment by cartland** [comment]
Hello, I suggest looking at the "UAMP" sample: https://github.com/googlesamples/android-UniversalMusicPlayer.

The UAMP sample contains a MediaBrowserService implementation that works with more Android features.
https://android-developers.googleblog.com/2018/06/a-new-universal-music-player.html
https://medium.com/androiddevelopers/making-the-uamp-sample-an-instant-app-30c3f0a050af

If you still see this issue in the UAMP sample, please open an issue there. Thank you!
