### ISSUE TITLE
Playback slider resets to 0 after re-opening activity

### ISSUE THREAD

**Issue by dsonck92** [googlesamples/android-MediaBrowserService#4]
On OnePlus 2 running Android 7.1.2, when the MainActivity is opened after closing it through back, the slider resets to 0 and won't animate.

**Comment by cartland** [comment]
Hello, I suggest looking at the "UAMP" sample: https://github.com/googlesamples/android-UniversalMusicPlayer.

The UAMP sample contains a MediaBrowserService implementation that works with more Android features.
https://android-developers.googleblog.com/2018/06/a-new-universal-music-player.html
https://medium.com/androiddevelopers/making-the-uamp-sample-an-instant-app-30c3f0a050af

If you still see this issue in the UAMP sample, please open an issue there. Thank you!
