### ISSUE TITLE
Notification in huawei device crash

### ISSUE THREAD

**Issue by Nestorsf** [googlesamples/android-MediaBrowserService#5]
I am test this example, when I press play button the app crash.
log: 
Bad notification posted from package com.example.android.mediasession: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.example.android.mediasession user=UserHandle{0} id=412 tag=null score=0 key=0|com.example.android.mediasession|412|null|10125: Notification(pri=0 contentView=com.example.android.mediasession/0x109007e vibrate=null sound=null defaults=0x0 flags=0x62 color=0xffe91e63 category=transport actions=3 vis=PUBLIC))

**Comment by cartland** [comment]
Hello, I suggest looking at the "UAMP" sample: https://github.com/googlesamples/android-UniversalMusicPlayer.

The UAMP sample contains a MediaBrowserService implementation that works with more Android features.
https://android-developers.googleblog.com/2018/06/a-new-universal-music-player.html
https://medium.com/androiddevelopers/making-the-uamp-sample-an-instant-app-30c3f0a050af

If you still see this issue in the UAMP sample, please open an issue there. Thank you!
