### ISSUE TITLE
Where to load music library from json?

### ISSUE THREAD

**Issue by limaho** [googlesamples/android-MediaBrowserService#7]
Hello, I am running this example, and I am studying this code. I want to know what is the best way to load my music library. I saw that the MediaItems are being loading in MusicLibrary class with the 2 samples songs. 

What is the best way to load music from json? and also If I want to add new song to the json list how can I added to the queue?

Thanks.

**Comment by cartland** [comment]
Hello, I suggest looking at the "UAMP" sample: https://github.com/googlesamples/android-UniversalMusicPlayer.

The UAMP sample contains a MediaBrowserService implementation that works with more Android features.
https://android-developers.googleblog.com/2018/06/a-new-universal-music-player.html
https://medium.com/androiddevelopers/making-the-uamp-sample-an-instant-app-30c3f0a050af

There are many ways to add new content to your app. If you have issues modifying the UAMP sample to meet your needs, I suggest filing a bug in that repository. Thank you!
