### ISSUE TITLE
Why in android pie not running, whether you can update the browser media to run on android pie.

### ISSUE THREAD

**Issue by bambanghariantosianturi** [googlesamples/android-MediaBrowserService#9]

**Comment by cartland** [comment]
Hello, I suggest looking at the "UAMP" sample: https://github.com/googlesamples/android-UniversalMusicPlayer.

The UAMP sample contains a MediaBrowserService implementation that works with more Android features.
https://android-developers.googleblog.com/2018/06/a-new-universal-music-player.html
https://medium.com/androiddevelopers/making-the-uamp-sample-an-instant-app-30c3f0a050af
